### ISSUE TITLE
Action/render execution order

### ISSUE THREAD

**Issue by robaca** [yahoo/fluxible-router#112]
Fluxible router seems to behave differently for a specific route if the application is loaded first time or the route is activated via a call to NavigateAction.

On first load, the action is executed first and then the handler instance is rendered (expected behaviour). But on dispatch of navigateAction, first the handler is rendered and then the action executes.

**Comment by mridgway** [comment]
This is by design so that you could render loading states within your components while navigation is happening. Then you change the layout immediately and then fill sections of the page with data as it is loaded rather than having a wait followed by a full update.

With that said, you should be able to get the behavior you want by implementing `shouldComponentUpdate` in your app component that returns false when [`this.props.isNavigateComplete`](https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/docs/api/handleRoute.md#props-passed) is false. This would prevent rendering until the full navigation has finished.

**Comment by robaca** [comment]
Ok, that makes sense :-). Thanks for the fast feedback

**Comment by redonkulus** [comment]
@cmjartan FYI, I've added this to our FAQ page https://github.com/yahoo/fluxible/blob/master/docs/faq.md#why-does-routing-execution-order-change-based-on-first-load-vs-routing-via-navigateaction
